import { configDotenv } from 'dotenv';
configDotenv();

const production = {
  NODE_ENV: process.env.TESTIFY_NODE_ENV,
  PORT: process.env.TESTIFY_PORT,
  DATABASE_URL: process.env.TESTIFY_DATABASE_URL,
  JWT_SECRET: process.env.JWT_SECRET,
  CRYPTO_SECRET: process.env.TESTIFY_CRYPTO_SECRET,
  CRYPTO_TIME_STEP: process.env.TESTIFY_CRYPTO_TIME_STEP,
  CRYPTO_OTP_LENGTH: process.env.TESTIFY_CRYPTO_OTP_LENGTH,
  CRYPTO_HASH_ALGO: process.env.TESTIFY_CRYPTO_HASH_ALGO,
  SALT_ROUND: process.env.TESTIFY_SALT_ROUND,
  MAIL_FROM: process.env.TESTIFY_MAIL_FROM,
  MAIL_USER: process.env.TESTIFY_MAIL_USER,
  MAIL_APP_PASSWORD: process.env.TESTIFY_MAIL_APP_PASSWORD,
  REDIS_URL: process.env.TESTIFY_REDIS_URL,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
  FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL,
  FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY,
  FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
};

export default production;
